name: GNU Build

on:
    workflow_run:
        workflows: ["Restrict PR Sources"]
        types:
            - completed
    push:
        branches-ignore:
            - main

jobs:
    build:
        if: |
            (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
            (github.event_name == 'push')
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Configure and build
            # Create a build directory, configure the project with CMake, and build it
              run: |
                module load hdf5/1.14.6
                mkdir -p build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_GPU=OFF
                make
            - name: Run tests
            # Run tests to verify the build
              run: |
                cd build
                ctest --output-on-failure
